package app.core.engines.user_profile

import android.content.Context.*
import app.core.*
import app.core.AIOApp.Companion.INSTANCE
import app.core.AIOApp.Companion.aioDSLJsonInstance
import app.core.AIOApp.Companion.aioUserProfile
import app.core.engines.fst_serializer.FSTBuilder.fstConfig
import com.anggrayudi.storage.file.*
import com.dslplatform.json.*
import io.objectbox.annotation.*
import lib.files.FileSystemUtility.readStringFromInternalStorage
import lib.files.FileSystemUtility.saveStringToInternalStorage
import lib.process.*
import java.io.*
import kotlin.jvm.Transient

/**
 * Represents a user's profile data within the application.
 *
 * This class is designed to be a central repository for user-specific information,
 * such as authentication status and personal details. It supports multiple persistence
 * mechanisms to ensure data integrity and backward compatibility.
 *
 * The data is persisted in three ways:
 * 1.  **ObjectBox Database:** As an `@Entity`, it is stored in a structured, efficient database.
 * 2.  **JSON File:** A human-readable JSON representation (`user_profile.json`) is saved
 *     in the app's internal storage for easy debugging and potential cross-platform use.
 * 3.  **Binary File:** A serialized binary format (`user_profile.dat`) is used for fast
 *     read/write operations, leveraging FST serialization.
 *
 * The class includes logic to read from older formats (binary, then JSON) and migrate
 * the data to the current persistence layers upon initialization.
 *
 * @property id The unique identifier for the user profile entry in the local ObjectBox database.
 * @property uniqueUserServerId A unique ID assigned by the server to identify the user across devices.
 *           Null if not available.
 * @property isUserCurrentlyLoggedIn A flag indicating whether the user is currently signed into their account.
 * @property userFullName The full name of the user. Null if not provided.
 * @property userEmailAddress The email address associated with the user's account. Null if not provided.
 * @property userPhoneNumber The phone number associated with the user's account. Null if not provided.
 */
@CompiledJson
@Entity
class AIOUserProfile : Serializable {
	
	/**
	 * Logger instance for this class. Marked as `@Transient` to exclude it from serialization.
	 */
	@Transient
	private val logger = LogHelperUtils.from(javaClass)
	
	/**
	 * The unique identifier for this user profile entry in the local ObjectBox database.
	 *
	 * This ID is automatically generated by ObjectBox when the profile is first saved
	 * and serves as the primary key for database operations. It is not intended for use
	 * as a server-side identifier.
	 */
	@Id
	@JvmField
	@JsonAttribute(name = "id")
	var id: Long = 0L
	
	/**
	 * A unique, server-assigned identifier for the user, sourced from Supabase Auth.
	 *
	 * This ID (often a UUID) is the primary key for the user in the remote database
	 * and is used to consistently identify them across different devices or sessions.
	 *
	 * It remains `null` until the user successfully authenticates and the ID is retrieved
	 * from the server.
	 *
	 * @see isSupabaseLinked
	 */
	@JvmField
	@JsonAttribute(name = "uniqueUserServerId")
	var uniqueUserServerId: String = ""
	
	/**
	 * A flag indicating the user's current authentication status.
	 *
	 * This property is `true` when the user has an active, authenticated session,
	 * meaning they are successfully signed into their account. It is `false` if the
	 * user is logged out or the session is invalid. It serves as a quick, client-side
	 * check for the login state across the application.
	 *
	 * Defaults to `false`.
	 */
	@JvmField
	@JsonAttribute(name = "isUserCurrentlyLoggedIn")
	var isUserCurrentlyLoggedIn: Boolean = false
	
	/**
	 * A flag indicating whether the user's account has been verified through any method.
	 *
	 * This property is a general-purpose flag that becomes `true` if the user completes
	 * any verification process, such as confirming an email (`isEmailVerified`) or a
	 * phone number (`isPhoneVerified`). It serves as a quick, consolidated check for
	 * overall account verification status.
	 *
	 * This value is typically derived from other specific verification flags and defaults
	 * to `false`.
	 */
	@JvmField
	@JsonAttribute(name = "isUserAccountVerified")
	var isUserAccountVerified: Boolean = false
	
	/**
	 * The full name of the user, as sourced from Supabase user metadata.
	 *
	 * This value is extracted from the `user.user_metadata` object, typically from a
	 * key such as `full_name`. It is `null` if the user has not provided their name
	 * or if the metadata has not been fetched.
	 */
	@JvmField
	@JsonAttribute(name = "userFullName")
	var userFullName: String = ""
	
	/**
	 * A flag indicating whether the user's email address has been verified.
	 *
	 * This property is `true` if the user has completed the email verification process
	 * (e.g., by clicking a link in a confirmation email), and `false` otherwise. It can be
	 * used to control access to features that require a verified email. Defaults to `false`.
	 *
	 * This value is typically synchronized with the `email_confirmed_at` timestamp from
	 * the authentication provider (e.g., Supabase). A non-null timestamp implies this flag
	 * should be `true`.
	 *
	 * @see emailVerifiedAt
	 */
	@JvmField
	@JsonAttribute(name = "isEmailVerified")
	var isEmailVerified: Boolean = false
	
	/**
	 * The timestamp when the user's email address was verified, in ISO-8601 format.
	 *
	 * This value is populated by Supabase upon successful email verification. It remains `null`
	 * if the user has not verified their email or if email-based authentication is not used.
	 *
	 * Example: "2023-10-26T10:00:00Z".
	 */
	@JvmField
	@JsonAttribute(name = "emailVerifiedAt")
	var emailVerifiedAt: String = ""
	
	/**
	 * The email address associated with the user's account.
	 *
	 * This value is populated during login or registration and is sourced from the
	 * Supabase user object. It remains `null` if the user is not logged in, has not
	 * provided an email, or uses a different authentication method (e.g., phone).
	 */
	@JvmField
	@JsonAttribute(name = "userEmailAddress")
	var userEmailAddress: String = ""
	
	/**
	 * Indicates whether the user's phone number has been successfully verified.
	 *
	 * This flag is `true` if the user has completed the phone verification process,
	 * typically by submitting an OTP (One-Time Password) received via SMS. A `false`
	 * value indicates the phone number is either unverified or has not been provided.
	 * This property is distinct from `isEmailVerified` and defaults to `false`.
	 */
	@JvmField
	@JsonAttribute(name = "isPhoneVerified")
	var isPhoneVerified: Boolean = false
	
	/**
	 * The timestamp when the user's phone number was verified on Supabase, in ISO-8601 format.
	 *
	 * This value is populated by Supabase upon successful phone number verification (e.g., via OTP).
	 * A non-null value indicates that the verification process was completed. It remains `null`
	 * if the user has not verified their phone number.
	 */
	@JvmField
	@JsonAttribute(name = "phoneVerifiedAt")
	var phoneVerifiedAt: String = ""
	
	/**
	 * The phone number associated with the user's account, formatted in the E.164 standard.
	 *
	 * This value is sourced from the Supabase user object and is populated during login
	 * or registration. It includes the country code. The property will be an empty string
	 * if the user has not provided a phone number or used a different authentication method.
	 *
	 * Example: `+11234567890`.
	 *
	 * @see isPhoneVerified
	 * @see phoneVerifiedAt
	 */
	@JvmField
	@JsonAttribute(name = "userPhoneNumber")
	var userPhoneNumber: String = ""
	
	/**
	 * The timestamp indicating when the user's account was created in Supabase.
	 *
	 * This value is sourced directly from the Supabase `user.createdAt` property and
	 * represents the server-side timestamp of account creation. It is formatted as an
	 * ISO-8601 string (e.g., "2023-10-26T10:00:00Z").
	 *
	 * This property will be `null` if the user is not logged in or if the data has not
	 * yet been fetched from the server.
	 */
	@JvmField
	@JsonAttribute(name = "supabaseAccountCreatedAt")
	var supabaseAccountCreatedAt: String = ""
	
	/**
	 * The timestamp of the user's last successful sign-in on Supabase, in ISO-8601 format.
	 *
	 * This value is automatically updated by Supabase on each successful authentication
	 * and is sourced from the `user.last_sign_in_at` field. It is useful for auditing,
	 * session management, or displaying activity information to the user.
	 * Remains `null` if the user has never signed in.
	 */
	@JvmField
	@JsonAttribute(name = "lastSupabaseLoginAt")
	var lastSupabaseLoginAt: String = ""
	
	/**
	 * The timestamp indicating the last time the user's data was updated on Supabase,
	 * in ISO-8601 format.
	 *
	 * This value is sourced from the `user.updated_at` property and reflects server-side
	 * changes to the user object, such as a modified email, password, or metadata.
	 * It is useful for determining if the local user profile data is stale and needs
	 * to be refreshed from the server.
	 *
	 * Remains `null` if the user's data has never been updated post-creation.
	 */
	@JvmField
	@JsonAttribute(name = "lastTimeUpdatedWithSupabase")
	var lastTimeUpdatedWithSupabase: Long = 0L
	
	/**
	 * A flag indicating whether this local user profile is successfully linked
	 * to a Supabase user account.
	 *
	 * This becomes `true` after a successful authentication event, such as OTP
	 * verification or social login, which confirms the local session is tied
	 * to a valid remote user. It should remain `false` for anonymous or
	 * unverified sessions.
	 */
	@JvmField
	@JsonAttribute(name = "isSupabaseLinked")
	var isSupabaseLinked: Boolean = false
	
	/**
	 * Arbitrary user-defined metadata from Supabase, stored as a raw JSON string.
	 *
	 * This property holds the `user.user_metadata` object from a Supabase authentication
	 * response. It is stored as a string to preserve the original JSON structure, allowing
	 * for flexible parsing of custom fields.
	 *
	 * The metadata typically contains profile-related information such as display name,
	 * avatar URL, or other custom attributes defined by the application.
	 *
	 * Example JSON structure:
	 * ```json
	 * {
	 *   "full_name": "John Doe",
	 *   "avatar_url": "https://example.com/avatar.png"
	 * }
	 * ```
	 */
	@JvmField
	@JsonAttribute(name = "supabaseUserMetadata")
	var supabaseUserMetadata: String = ""
	
	/**
	 * Application-level metadata assigned by Supabase, stored as a JSON string.
	 *
	 * This field contains non-user-editable data managed by the backend, such as
	 * subscription status, user roles (e.g., "admin"), or other system-level flags.
	 * The raw value is a JSON string that must be parsed to access its contents.
	 *
	 * Example JSON structure:
	 * ```json
	 * {
	 *   "provider": "email",
	 *   "providers": ["email"]
	 * }
	 * ```
	 */
	@JvmField
	@JsonAttribute(name = "supabaseAppMetadata")
	var supabaseAppMetadata: String = ""
	
	/**
	 * Asynchronously reads the user profile from legacy storage formats.
	 *
	 * This function initiates a background process to load the user profile from older
	 * persistence layers, ensuring backward compatibility. It first attempts to load from a
	 * binary file (`user_profile.dat`), and if that fails or the file doesn't exist, it falls
	 * back to a JSON file (`user_profile.json`).
	 *
	 * The operation is performed on a background thread with a timeout to prevent blocking
	 * the main thread. If a profile is successfully loaded, it is migrated to the current
	 * persistence layers (ObjectBox, updated JSON/binary files).
	 *
	 * @see initializeLegacyDataParser
	 */
	fun readObjectFromStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 1200,
			codeBlock = {
				initializeLegacyDataParser()
			})
	}
	
	/**
	 * Initializes the user profile by attempting to load data from legacy storage formats.
	 *
	 * This function serves as a migration path for user data stored in older versions of the app.
	 * It follows a specific priority order for loading:
	 * 1.  **Binary File (`user_profile.dat`):** It first tries to load the user profile from a
	 *     fast, FST-serialized binary file. If successful, it populates the `aioUserProfile`
	 *     instance and triggers an update to persist the data in the current storage formats
	 *     (ObjectBox, JSON).
	 * 2.  **JSON File (`user_profile.json`):** If the binary file is not found or fails to load,
	 *     it falls back to reading a human-readable JSON file. If this is successful, the data
	 *     is loaded and similarly persisted to modern storage layers.
	 *
	 * If neither legacy file exists or can be parsed, the function completes without loading
	 * any data, and the application will proceed with a default or new user profile. All
	 * potential errors during file I/O or parsing are caught and logged to prevent crashes.
	 */
	private fun initializeLegacyDataParser() {
		try {
			var isBinaryFileValid = false
			val internalDir = AIOApp.internalDataFolder
			val userProfileBinaryDataFile = internalDir.findFile(USER_PROFILE_FILE_NAME_BINARY)
			if (userProfileBinaryDataFile != null && userProfileBinaryDataFile.exists()) {
				logger.d("Found binary user profile file, attempting to load")
				val absolutePath = userProfileBinaryDataFile.getAbsolutePath(INSTANCE)
				val objectInMemory = loadFromBinary(File(absolutePath))
				
				if (objectInMemory != null) {
					logger.d("Successfully loaded user profile from binary format")
					aioUserProfile = objectInMemory
					aioUserProfile.updateInStorage()
					isBinaryFileValid = true
				} else {
					logger.d("Failed to load user profile from binary format")
				}
			}
			
			if (!isBinaryFileValid) {
				logger.d("Attempting to load user profile from JSON format")
				
				readStringFromInternalStorage(USER_PROFILE_FILE_NAME_JSON).let { jsonString ->
					if (jsonString.isNotEmpty()) {
						convertJSONStringToClass(jsonString = jsonString).let {
							logger.d("Successfully loaded user profile from JSON format")
							aioUserProfile = it
							aioUserProfile.updateInStorage()
						}
					} else {
						logger.d("No JSON user profile found or file empty")
					}
				}
			}
			
		} catch (error: Exception) {
			logger.e("Error reading user profile from storage: ${error.message}", error)
		}
	}
	
	/**
	 * Asynchronously persists the current state of the user profile to all configured storage layers.
	 *
	 * This function orchestrates the saving of the user profile to multiple destinations to ensure
	 * data integrity, redundancy, and backward compatibility. The destinations are:
	 * 1.  **ObjectBox Database:** The profile is saved as an entity, which is the primary and most
	 *     efficient persistence mechanism.
	 * 2.  **JSON File:** A human-readable JSON representation (`user_profile.json`) is stored for
	 *     debugging and fallback purposes.
	 * 3.  **Binary File:** A fast, serialized version (`user_profile.dat`) is saved using FST for
	 *     quick I/O and legacy support.
	 *
	 * The entire operation is executed on a background thread to avoid blocking the main UI thread.
	 * Any errors encountered during the process are caught and logged, preventing the app from crashing.
	 */
	fun updateInStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 100, codeBlock = {
			try {
				logger.d("Updating user profile in storage")
				saveToBinary(fileName = USER_PROFILE_FILE_NAME_BINARY)
				saveStringToInternalStorage(
					fileName = USER_PROFILE_FILE_NAME_JSON,
					data = convertClassToJSON()
				)
				AIOUserProfileDBManager.saveUserProfileInDB(userProfile = this)
				logger.d("User profile successfully updated in storage")
			} catch (error: Exception) {
				logger.e("Error updating user profile in storage: ${error.message}", error)
			}
		})
	}
	
	/**
	 * Serializes the current `AIOUserProfile` instance and saves it to a binary file
	 * in the application's private internal storage. This method uses FST (Fast-Serialization)
	 * for efficient and fast data persistence.
	 *
	 * The operation is synchronized to prevent concurrent write access. Any exceptions
	 * during the file writing process are caught and logged.
	 *
	 * @param fileName The name of the binary file (e.g., "user_profile.dat") where the
	 *                 serialized profile data will be stored.
	 */
	@Synchronized
	private fun saveToBinary(fileName: String) {
		try {
			logger.d("Saving user profile to binary file: $fileName")
			val fileOutputStream = INSTANCE.openFileOutput(fileName, MODE_PRIVATE)
			fileOutputStream.use { fos ->
				val bytes = fstConfig.asByteArray(this)
				fos.write(bytes)
				logger.d("Binary user profile saved successfully")
			}
		} catch (error: Exception) {
			logger.e("Error saving binary user profile: ${error.message}", error)
		}
	}
	
	/**
	 * Loads and deserializes the user profile from a binary file.
	 *
	 * This method reads a user profile from a binary file (`user_profile.dat`) serialized with
	 * FST (Fast-Serialization). It serves as a backward-compatibility layer to import data
	 * from the legacy binary persistence format.
	 *
	 * If the specified file does not exist, the function returns `null`.
	 *
	 * If any error occurs during file reading or deserialization (e.g., due to file corruption
	 * or a class structure mismatch), the corrupted file is deleted to prevent future load
	 * errors, and the function returns `null`.
	 *
	 * @param userProfileBinaryFile The [File] object pointing to the binary user profile.
	 * @return An `AIOUserProfile` instance if deserialization is successful; otherwise, `null`.
	 */
	private fun loadFromBinary(userProfileBinaryFile: File): AIOUserProfile? {
		if (!userProfileBinaryFile.exists()) {
			logger.d("Binary user profile file does not exist")
			return null
		}
		
		return try {
			logger.d("Loading user profile from binary file")
			val bytes = userProfileBinaryFile.readBytes()
			fstConfig.asObject(bytes).apply {
				logger.d("Successfully loaded user profile from binary file")
			} as AIOUserProfile
		} catch (error: Exception) {
			logger.e("Error loading binary user profile: ${error.message}", error)
			userProfileBinaryFile.delete()
			null
		}
	}
	
	/**
	 * Serializes the current `AIOUserProfile` instance into a JSON string.
	 *
	 * This function uses the `DslJson` library for efficient serialization. The output is a
	 * UTF-8 encoded JSON string that represents the state of this object. This is primarily
	 * used for persisting the user profile in a human-readable format for debugging
	 * and backward compatibility.
	 *
	 * @return A JSON string representation of the user profile.
	 */
	fun convertClassToJSON(): String {
		val jsonOutputStream = ByteArrayOutputStream(16 * 1024)
		logger.d("Converting user profile to JSON")
		jsonOutputStream.reset()
		aioDSLJsonInstance.serialize(this, jsonOutputStream)
		return jsonOutputStream.toString(Charsets.UTF_8.name())
	}
	
	/**
	 * Resets the user profile to its default state and clears all persisted data.
	 *
	 * This function performs a comprehensive reset by:
	 * 1.  Re-initializing the in-memory `aioUserProfile` instance to a new, empty object.
	 * 2.  Deleting the corresponding entry from the ObjectBox database.
	 * 3.  Deleting the legacy `user_profile.json` and `user_profile.dat` files from
	 *     internal storage to ensure no old data is loaded on the next app start.
	 *
	 * This is effectively a "logout and clear" operation, removing all traces of the
	 * current user's data from the device. The operation is performed asynchronously
	 * on a background thread to prevent blocking the UI.
	 */
	fun resetUserProfile() {
		uniqueUserServerId = ""
		isUserCurrentlyLoggedIn = false
		isUserAccountVerified = false
		userFullName = ""
		isEmailVerified = false
		emailVerifiedAt = ""
		userEmailAddress = ""
		isPhoneVerified = false
		phoneVerifiedAt = ""
		userPhoneNumber = ""
		supabaseAccountCreatedAt = ""
		lastSupabaseLoginAt = ""
		isSupabaseLinked = false
		supabaseUserMetadata = ""
		supabaseAppMetadata = ""
		lastTimeUpdatedWithSupabase = 0L
	}
	
	companion object {
		
		/**
		 * A logger instance for logging events and errors related to the AIOUserProfile class,
		 * primarily used for static operations within the companion object.
		 */
		private val logger = LogHelperUtils.from(AIOUserProfile::class.java)
		
		/**
		 * Filename for the JSON representation of the user profile, stored in the app's internal storage.
		 * This file provides a human-readable backup and is used for debugging or as a fallback
		 * if other persistence methods fail.
		 */
		const val USER_PROFILE_FILE_NAME_JSON: String = "user_profile.json"
		
		/**
		 * The filename for the binary-serialized user profile data.
		 *
		 * This file stores the `AIOUserProfile` object in a fast, compact binary format using
		 * FST serialization. It is used as a legacy persistence method for quick read/write
		 * operations before migrating to or alongside the ObjectBox database.
		 *
		 * @see AIOUserProfile.saveToBinary
		 * @see AIOUserProfile.loadFromBinary
		 */
		const val USER_PROFILE_FILE_NAME_BINARY: String = "user_profile.dat"
		
		/**
		 * Deserializes a JSON string into an [AIOUserProfile] object.
		 *
		 * This function takes a JSON representation of a user profile and converts it
		 * back into an `AIOUserProfile` instance using the DSL-JSON library. If the
		 * deserialization fails or the input string is empty/invalid, it returns a
		 * new, empty `AIOUserProfile` object to prevent null pointer exceptions.
		 *
		 * @param jsonString The JSON string to be deserialized.
		 * @return An [AIOUserProfile] object populated with data from the JSON string,
		 *         or a default `AIOUserProfile` instance if deserialization fails.
		 */
		@JvmStatic
		fun convertJSONStringToClass(jsonString: String): AIOUserProfile {
			logger.d("Converting JSON to user profile object")
			val inputStream = ByteArrayInputStream(jsonString.encodeToByteArray())
			val loadedUserProfile: AIOUserProfile = aioDSLJsonInstance
				.deserialize(AIOUserProfile::class.java, inputStream) ?: AIOUserProfile()
			return loadedUserProfile
		}
	}
}