package app.core.engines.youtube

import lib.networks.*
import lib.process.*
import okhttp3.RequestBody.Companion.toRequestBody
import org.schabi.newpipe.extractor.downloader.*
import org.schabi.newpipe.extractor.exceptions.*
import java.io.*

/**
 * A custom implementation of NewPipe's [Downloader] that bridges the NewPipe Extractor library
 * with the application's network layer.
 *
 * This implementation delegates all HTTP/HTTPS network operations to a shared, singleton OkHttp client
 * provided by [HttpClientProvider]. By using a centralized client, it ensures efficient resource
 * management, including connection pooling and caching, across the entire application.
 *
 * Key responsibilities:
 * - **Executing Network Requests:** Translates [org.schabi.newpipe.extractor.downloader.Request]
 *   objects from the extractor into OkHttp requests and executes them.
 * - **Response Translation:** Converts OkHttp responses back into the
 *   [org.schabi.newpipe.extractor.downloader.Response] format expected by the extractor.
 * - **Centralized Networking:** Leverages the app's standard [okhttp3.OkHttpClient] for all
 *   of NewPipe's data extraction needs (e.g., fetching video metadata, comments, and streams).
 * - **Debugging and Monitoring:** Integrates with the application's logging framework to provide
 *   visibility into the network traffic generated by the extractor.
 *
 * @see Downloader
 * @see HttpClientProvider
 */
class DefaultYTDownloaderImpl : Downloader() {
	
	/** Logger for this class, used for debugging and monitoring network requests. */
	private val logger = LogHelperUtils.from(javaClass)
	
	/**
	 * The singleton OkHttp client used for all network requests.
	 *
	 * This client is shared across the entire application to ensure efficient
	 * connection pooling, caching, and resource management. It is provided
	 * by [lib.networks.HttpClientProvider].
	 */
	private val okHttpClient = HttpClientProvider.okHttpClient
	
	/**
	 * Executes a network request using OkHttp and converts it into a NewPipe-compatible [Response].
	 *
	 * This method builds an OkHttp request from the provided NewPipe [Request],
	 * including the URL, HTTP method, headers, and an optional request body.
	 * It then executes the request using the shared [okHttpClient] and maps the
	 * resulting OkHttp response to NewPipe's [Response] format.
	 *
	 * Extensive logging is included to aid in debugging, capturing details about the
	 * outgoing request and the incoming response.
	 *
	 * @param request the [Request] to be executed, containing the URL, method, headers, and data.
	 * @return a [Response] object containing the HTTP status, headers, and response body.
	 * @throws IOException if a network or I/O error occurs during the request execution.
	 * @throws ReCaptchaException if the request is blocked by a reCAPTCHA challenge.
	 */
	@Throws(IOException::class, ReCaptchaException::class)
	override fun execute(request: Request): Response {
		val method = request.httpMethod().uppercase()
		logger.d("Executing $method request for URL: ${request.url()}")
		
		// Build OkHttp request
		val builder = okhttp3.Request.Builder().url(request.url())
		
		// Add headers
		request.headers().forEach { (key, values) ->
			values.forEach { value ->
				builder.addHeader(key, value)
				logger.d("Header added: $key=$value")
			}
		}
		
		// Set HTTP method and body efficiently
		when (method) {
			"HEAD" -> builder.head()
			"GET" -> builder.get()
			"POST" -> builder.post((request.dataToSend() ?: ByteArray(0)).toRequestBody())
			"PUT" -> builder.put((request.dataToSend() ?: ByteArray(0)).toRequestBody())
			
			"DELETE" -> {
				val data = request.dataToSend()
				if (data != null) builder.delete(data.toRequestBody()) else builder.delete()
			}
			
			else -> {
				logger.d("Unknown HTTP method '$method', defaulting to GET")
				builder.get()
			}
		}
		
		// Execute the HTTP request
		val okResponse: okhttp3.Response = okHttpClient.newCall(builder.build()).execute()
		logger.d("Response received: ${okResponse.code} from ${okResponse.request.url}")
		
		// Read response body
		val responseBody = okResponse.body.string()
		logger.d("Response body length: ${responseBody.length} characters")
		
		return Response(
			okResponse.code,
			okResponse.message,
			okResponse.headers.toMultimap(),
			responseBody,
			okResponse.request.url.toString()
		)
	}
}