package app.core.engines.youtube

import com.dslplatform.json.*
import io.objectbox.annotation.*
import lib.process.*
import java.io.*

/**
 * Data model representing a YouTube video with its complete metadata.
 * This entity is stored in the local database using ObjectBox and supports JSON serialization
 * for network transmission or data persistence.
 */
@CompiledJson
@Entity
class YouTubeVideoDataModel(
	/** Unique database identifier automatically generated by ObjectBox */
	@Id
	@JvmField
	@param:JsonAttribute(name = "id")
	var id: Long = 0L,
	
	/** Timestamp in milliseconds when this record was last modified */
	@JvmField
	@param:JsonAttribute(name = "lastModifiedTimeDate")
	var lastModifiedTimeDate: Long = 0L,
	
	/** Complete URL of the YouTube video (e.g., https://youtube.com/watch?v=abc123) */
	@JvmField
	@param:JsonAttribute(name = "videoUrl")
	var videoUrl: String = "",
	
	/** Title of the YouTube video (nullable for partial data) */
	@JvmField
	@param:JsonAttribute(name = "videoTitle")
	var videoTitle: String? = null,
	
	/** URL to the video's thumbnail image in various resolutions */
	@JvmField
	@param:JsonAttribute(name = "videoThumbnailUrl")
	var videoThumbnailUrl: String? = null,
	
	/** Full description text from the YouTube video page */
	@JvmField
	@param:JsonAttribute(name = "videoDescription")
	var videoDescription: String? = null,
	
	/** Formatted duration string (e.g., "10:30" for 10 minutes 30 seconds) */
	@JvmField
	@param:JsonAttribute(name = "videoDuration")
	var videoDuration: String? = null,
	
	/** Formatted view count (e.g., "1.5M views", "250K views") */
	@JvmField
	@param:JsonAttribute(name = "videoViewsCount")
	var videoViewsCount: String? = null,
	
	/** Name of the YouTube channel that uploaded the video */
	@JvmField
	@param:JsonAttribute(name = "videoChannelName")
	var videoChannelName: String? = null,
	@JvmField
	@param:JsonAttribute(name = "videoChannelThumbnail")
	var videoChannelThumbnail: String? = null,
	
) : Serializable {
	
	/** Logger instance for tracking operations on this specific model */
	@Transient
	private val logger = LogHelperUtils.from(javaClass)
	
	/**
	 * Saves or updates this YouTube video model in the local database.
	 * The operation runs asynchronously in the background with a 500ms timeout
	 * and provides success/error callbacks for result handling.
	 *
	 * Use this method to persist video metadata changes or add new video records.
	 * The video's ID is automatically handled by the database manager.
	 */
	fun updateInStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 500,
			codeBlock = {
				YTVideosModelsDBManager.saveYouTubeVideoModelsInDB(
					youTubeVideoModel = this,
					listener = object : YTVideosModelsDBManager.OnSaveResultListener {
						override fun onSuccess(savedId: Long) {
							logger.d("YouTube video model saved to storage successfully.")
						}
						
						override fun onError(error: Exception) {
							logger.d("Failed to save YouTube video model to storage.")
						}
					}
				)
			}
		)
	}
	
	/**
	 * Removes this YouTube video model from the local database.
	 * Uses the video's unique ID to locate and delete the corresponding record.
	 * The operation runs asynchronously in the background with a 500ms timeout.
	 *
	 * @return Boolean result is logged but not returned for asynchronous operation
	 */
	fun clearFromStorage() {
		ThreadsUtility.executeInBackground(
			timeOutInMilli = 500,
			codeBlock = {
				val isDeleted = YTVideosModelsDBManager.deleteYouTubeVideoById(id)
				logger.d(
					"Deletion of YouTube video model from storage was " +
						"${if (isDeleted) "successful" else "failed"}."
				)
			}
		)
	}
}